export enum ExitCode {
  SUCCESS = 0,
  GENERIC_ERROR = 1,
  APP_NOT_RUNNING = 2,
  INVALID_COMMAND = 3,
  CONFIG_ERROR = 4,
  AGENT_FAILED = 10,
  AGENT_TIMED_OUT = 11,
  AGENT_NOT_FOUND = 12,
  BLOCKED_BY_NETWORK_GUARD = 20,
  NETWORK_GUARD_ERROR = 21,
  SKIPPED_BY_LIMITS_GUARD = 30,
  LIMITS_PROVIDER_UNAVAILABLE = 31,
  LIMITS_PROVIDER_INVALID_DATA = 32
}
